[package]
name = "clipmanager_rs"
version = "0.1.0"
edition = "2021"



[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
iced = "0.6.0"
diesel = { version = "2.0.0", features = ["sqlite"] }
diesel_migrations = { version="2.0.0", features=["sqlite"]}

